sudo: false
language: node_js
node_js:
  - '15'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run build
  - npm run test
env:
  - TWITTER_API_KEY=fake TWITTER_API_KEY_SECRET=fake TWITTER_ACCESS_TOKEN=fake TWITTER_ACCESS_TOKEN_SECRET=fake
